In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rc
rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

/var/folders/qv/tqmmyp0s5dj996k_tcvqmtqm0000gn/T/ipykernel_2166/900850709.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [4]:
df = pd.read_excel('/Users/hj/Documents/무제/실전프로젝트/Spotify_data.xlsx')
df

Age  Gender spotify_usage_period  \
0    20-35  Female    More than 2 years   
1    12-20    Male    More than 2 years   
2    35-60  Others   6 months to 1 year   
3    20-35  Female    1 year to 2 years   
4    20-35  Female    1 year to 2 years   
..     ...     ...                  ...   
515  20-35  Female    More than 2 years   
516  20-35  Female    More than 2 years   
517  20-35  Female    More than 2 years   
518  20-35  Female   6 months to 1 year   
519  20-35  Female    More than 2 years   

                             spotify_listening_device  \
0                  Smart speakers or voice assistants   
1                                  Computer or laptop   
2                  Smart speakers or voice assistants   
3      Smartphone, Smart speakers or voice assistants   
4                                          Smartphone   
..                                                ...   
515  Smartphone, Computer or laptop, Wearable devices   
516                    Smartphone, Computer or laptop   
517                                        Smartphone   
518                                        Smartphone   
519                    Smartphone, Computer or laptop   

       spotify_subscription_plan premium_sub_willingness  \
0            Free (ad-supported)                     Yes   
1            Free (ad-supported)                     Yes   
2            Free (ad-supported)                     Yes   
3            Free (ad-supported)                      No   
4            Free (ad-supported)                      No   
..                           ...                     ...   
515          Free (ad-supported)                     Yes   
516          Free (ad-supported)                     Yes   
517          Free (ad-supported)                      No   
518  Premium (paid subscription)                     Yes   
519  Premium (paid subscription)                     Yes   

             preffered_premium_plan preferred_listening_content  \
0          Family Plan-Rs 179/month                     Podcast   
1    Individual Plan- Rs 119/ month                     Podcast   
2          Student Plan-Rs 59/month                     Podcast   
3                               NaN                       Music   
4                               NaN                       Music   
..                              ...                         ...   
515        Student Plan-Rs 59/month                       Music   
516        Student Plan-Rs 59/month                       Music   
517        Student Plan-Rs 59/month                       Music   
518  Individual Plan- Rs 119/ month                       Music   
519        Student Plan-Rs 59/month                       Music   

    fav_music_genre music_time_slot  \
0            Melody           Night   
1               Rap       Afternoon   
2               Pop           Night   
3            Melody           Night   
4            Melody           Night   
..              ...             ...   
515             Pop         Morning   
516             Pop           Night   
517             Pop           Night   
518          Melody           Night   
519             Pop           Night   

                                music_Influencial_mood  \
0                                Sadness or melancholy   
1                         Social gatherings or parties   
2                         Relaxation and stress relief   
3    Relaxation and stress relief, Social gathering...   
4                         Relaxation and stress relief   
..                                                 ...   
515  Uplifting and motivational, Sadness or melancholy   
516  Relaxation and stress relief, Uplifting and mo...   
517                       Relaxation and stress relief   
518  Relaxation and stress relief, Uplifting and mo...   
519  Relaxation and stress relief, Sadness or melan...   

                                   music_lis_frequency  \
0                                         leisure time 

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Age                          520 non-null    object
 1   Gender                       520 non-null    object
 2   spotify_usage_period         520 non-null    object
 3   spotify_listening_device     520 non-null    object
 4   spotify_subscription_plan    520 non-null    object
 5   premium_sub_willingness      520 non-null    object
 6   preffered_premium_plan       312 non-null    object
 7   preferred_listening_content  520 non-null    object
 8   fav_music_genre              520 non-null    object
 9   music_time_slot              520 non-null    object
 10  music_Influencial_mood       520 non-null    object
 11  music_lis_frequency          520 non-null    object
 12  music_expl_method            520 non-null    object
 13  music_recc_rating            520 no

> preffered_premium_plan : 프리미엄이거나 프리미엄을 받을 의향이 있는 경우 구독료로 얼마를 지불합니까? 520 중 312
- 가격 컬럼 따로 분리시키기
- plan 별 혜택 찾기

In [6]:
df['preffered_premium_plan'].value_counts()

preffered_premium_plan
Individual Plan- Rs 119/ month    95
Student Plan-Rs 59/month          94
Duo plan- Rs 149/month            84
Family Plan-Rs 179/month          39
Name: count, dtype: int64

> fav_pod_genre : 팟캐스트 중 어떤 장르를 가장 좋아하시나요? 520 중 372

In [7]:
df['fav_pod_genre'].value_counts()

fav_pod_genre
Comedy                                              107
Lifestyle and Health                                102
Health and Fitness                                   78
Sports                                               51
Food and cooking                                     20
Finance related and current affairs                   1
Educational                                           1
Self help                                             1
Novels                                                1
Political, informative, topics that interests me      1
Murder Mystery                                        1
Technology                                            1
Spiritual and devotional                              1
General knowledge                                     1
Dance and Relevant cases                              1
Informative stuff                                     1
Everything                                            1
Business                          

> preffered_pod_format: 선호하는 팟캐스트 형식

In [9]:
df['preffered_pod_format'].value_counts()

preffered_pod_format
Story telling     152
Conversational    105
Interview          74
Educational        49
Name: count, dtype: int64

> pod_host_preference : 알려지지 않은 인물의 팟캐스트를 듣는 것을 더 선호합니까, 아니면 유명인이 호스팅하는 팟캐스트를 선호합니까?

In [10]:
df['pod_host_preference'].value_counts()

pod_host_preference
Both                      180
Well known individuals    114
unknown Podcasters         85
Name: count, dtype: int64

> preffered_pod_duration : 짧은 팟캐스트 에피소드(30분 미만) 또는 긴 에피소드(30분 이상)를 선호합니까?

In [11]:
df['preffered_pod_duration'].value_counts()

preffered_pod_duration
Shorter    191
Both       117
Longer      83
Name: count, dtype: int64

In [12]:
df['Age'].value_counts()

Age
20-35    422
12-20     71
35-60     23
6-12       3
60+        1
Name: count, dtype: int64

In [76]:
df['spotify_usage_period'].value_counts()

spotify_usage_period
More than 2 years     169
1 year to 2 years     141
6 months to 1 year    119
Less than 6 months     91
Name: count, dtype: int64

In [23]:
age_group = df[['Age']].groupby('Age').size()

plt.figure(figsize=(5, 5))
age_group.plot(kind='bar', color='skyblue')

<Axes: xlabel='Age'>

In [25]:
df.describe(include='all')

Age  Gender spotify_usage_period spotify_listening_device  \
count     520     520                  520                      520   
unique      5       3                    4                       15   
top     20-35  Female    More than 2 years               Smartphone   
freq      422     391                  169                      300   
mean      NaN     NaN                  NaN                      NaN   
std       NaN     NaN                  NaN                      NaN   
min       NaN     NaN                  NaN                      NaN   
25%       NaN     NaN                  NaN                      NaN   
50%       NaN     NaN                  NaN                      NaN   
75%       NaN     NaN                  NaN                      NaN   
max       NaN     NaN                  NaN                      NaN   

       spotify_subscription_plan premium_sub_willingness  \
count                        520                     520   
unique                         2                       2   
top          Free (ad-supported)                      No   
freq                         424                     334   
mean                         NaN                     NaN   
std                          NaN                     NaN   
min                          NaN                     NaN   
25%                          NaN                     NaN   
50%                          NaN                     NaN   
75%                          NaN                     NaN   
max                          NaN                     NaN   

                preffered_premium_plan preferred_listening_content  \
count                              312                         520   
unique                               4                           2   
top     Individual Plan- Rs 119/ month                       Music   
freq                                95                         410   
mean                               NaN                         NaN   
std                                NaN                         NaN   
min                                NaN                         NaN   
25%                                NaN                         NaN   
50%                                NaN                         NaN   
75%                                NaN                         NaN   
max                                NaN                         NaN   

       fav_music_genre music_time_slot        music_Influencial_mood  \
count              520             520                           520   
unique              11               3                            15   
top             Melody           Night  Relaxation and stress relief   
freq               259             312                           195   
mean               NaN             NaN                           NaN   
std                NaN             NaN                           NaN   
min                NaN             NaN                           NaN   
25%                NaN             NaN                           NaN   
50%                NaN             NaN                           NaN   
75%                NaN             NaN                           NaN   
max                NaN             NaN                           NaN   

       music_lis_frequency music_expl_method  music_recc_rating  \
count                  520               520         520.000000   
unique                  35                20                NaN   
top        While Traveling   recommendations                NaN   
freq                   111               113                NaN   
mean                   NaN               NaN           3.503846   
std                    NaN               NaN           0.979552   
min                    NaN               NaN           1.000000   
25%                    NaN               NaN           3.000000   
50%                    NaN               NaN           3.500000   
75%                    NaN               NaN           4.000

In [26]:
df['fav_music_genre'].value_counts()

fav_music_genre
Melody                       259
classical                     87
Pop                           85
Rap                           55
Electronic/Dance              16
All                            6
Rock                           4
Kpop                           4
Classical & melody, dance      2
Old songs                      1
trending songs random          1
Name: count, dtype: int64

### 주 고객층 20대
---

In [29]:
twenty = df[df['Age']=='20-35']
twenty

Age  Gender spotify_usage_period  \
0    20-35  Female    More than 2 years   
3    20-35  Female    1 year to 2 years   
4    20-35  Female    1 year to 2 years   
5    20-35    Male    More than 2 years   
6    20-35  Female    1 year to 2 years   
..     ...     ...                  ...   
515  20-35  Female    More than 2 years   
516  20-35  Female    More than 2 years   
517  20-35  Female    More than 2 years   
518  20-35  Female   6 months to 1 year   
519  20-35  Female    More than 2 years   

                             spotify_listening_device  \
0                  Smart speakers or voice assistants   
3      Smartphone, Smart speakers or voice assistants   
4                                          Smartphone   
5                                          Smartphone   
6                                          Smartphone   
..                                                ...   
515  Smartphone, Computer or laptop, Wearable devices   
516                    Smartphone, Computer or laptop   
517                                        Smartphone   
518                                        Smartphone   
519                    Smartphone, Computer or laptop   

       spotify_subscription_plan premium_sub_willingness  \
0            Free (ad-supported)                     Yes   
3            Free (ad-supported)                      No   
4            Free (ad-supported)                      No   
5            Free (ad-supported)                      No   
6            Free (ad-supported)                      No   
..                           ...                     ...   
515          Free (ad-supported)                     Yes   
516          Free (ad-supported)                     Yes   
517          Free (ad-supported)                      No   
518  Premium (paid subscription)                     Yes   
519  Premium (paid subscription)                     Yes   

             preffered_premium_plan preferred_listening_content  \
0          Family Plan-Rs 179/month                     Podcast   
3                               NaN                       Music   
4                               NaN                       Music   
5                               NaN                       Music   
6                               NaN                       Music   
..                              ...                         ...   
515        Student Plan-Rs 59/month                       Music   
516        Student Plan-Rs 59/month                       Music   
517        Student Plan-Rs 59/month                       Music   
518  Individual Plan- Rs 119/ month                       Music   
519        Student Plan-Rs 59/month                       Music   

    fav_music_genre music_time_slot  \
0            Melody           Night   
3            Melody           Night   
4            Melody           Night   
5               Pop           Night   
6            Melody         Morning   
..              ...             ...   
515             Pop         Morning   
516             Pop           Night   
517             Pop           Night   
518          Melody           Night   
519             Pop           Night   

                                music_Influencial_mood  \
0                                Sadness or melancholy   
3    Relaxation and stress relief, Social gathering...   
4                         Relaxation and stress relief   
5                           Uplifting and motivational   
6                         Relaxation and stress relief   
..                                                 ...   
515  Uplifting and motivational, Sadness or melancholy   
516  Relaxation and stress relief, Uplifting and mo...   
517                       Relaxation and stress relief   
518  Relaxation and stress relief, Uplifting and mo...   
519  Relaxation and stress relief, Sadness or melan...   

                                   music_lis_frequency  \
0                                         leisure time 

In [30]:
twenty.describe(include='all')

Age  Gender spotify_usage_period spotify_listening_device  \
count     422     422                  422                      422   
unique      1       3                    4                       15   
top     20-35  Female    More than 2 years               Smartphone   
freq      422     331                  149                      270   
mean      NaN     NaN                  NaN                      NaN   
std       NaN     NaN                  NaN                      NaN   
min       NaN     NaN                  NaN                      NaN   
25%       NaN     NaN                  NaN                      NaN   
50%       NaN     NaN                  NaN                      NaN   
75%       NaN     NaN                  NaN                      NaN   
max       NaN     NaN                  NaN                      NaN   

       spotify_subscription_plan premium_sub_willingness  \
count                        422                     422   
unique                         2                       2   
top          Free (ad-supported)                      No   
freq                         356                     281   
mean                         NaN                     NaN   
std                          NaN                     NaN   
min                          NaN                     NaN   
25%                          NaN                     NaN   
50%                          NaN                     NaN   
75%                          NaN                     NaN   
max                          NaN                     NaN   

                preffered_premium_plan preferred_listening_content  \
count                              245                         422   
unique                               4                           2   
top     Individual Plan- Rs 119/ month                       Music   
freq                                81                         361   
mean                               NaN                         NaN   
std                                NaN                         NaN   
min                                NaN                         NaN   
25%                                NaN                         NaN   
50%                                NaN                         NaN   
75%                                NaN                         NaN   
max                                NaN                         NaN   

       fav_music_genre music_time_slot        music_Influencial_mood  \
count              422             422                           422   
unique              10               3                            15   
top             Melody           Night  Relaxation and stress relief   
freq               231             281                           167   
mean               NaN             NaN                           NaN   
std                NaN             NaN                           NaN   
min                NaN             NaN                           NaN   
25%                NaN             NaN                           NaN   
50%                NaN             NaN                           NaN   
75%                NaN             NaN                           NaN   
max                NaN             NaN                           NaN   

       music_lis_frequency music_expl_method  music_recc_rating  \
count                  422               422         422.000000   
unique                  35                20                NaN   
top        While Traveling   recommendations                NaN   
freq                    86               100                NaN   
mean                   NaN               NaN           3.578199   
std                    NaN               NaN           0.973423   
min                    NaN               NaN           1.000000   
25%                    NaN               NaN           3.000000   
50%                    NaN               NaN           4.000000   
75%                    NaN               NaN           4.000

In [31]:
twenty['spotify_subscription_plan'].value_counts()

spotify_subscription_plan
Free (ad-supported)            356
Premium (paid subscription)     66
Name: count, dtype: int64

In [33]:
# 무료 요금제 사용률
356 / (356+66) * 100

84.36018957345972

In [35]:
twenty['premium_sub_willingness'].value_counts()

premium_sub_willingness
No     281
Yes    141
Name: count, dtype: int64

In [39]:
# 20대 이탈률 (프리미엄 사용중이나, 앞으로 구독의향 없는 집단)

twenty_bounce = twenty[(twenty['spotify_subscription_plan']=='Premium (paid subscription)') & (twenty['premium_sub_willingness']=='No')]
twenty_bounce

## 사용중인 프리미엄 구독 종류가, 듀오, 패밀리 플랜

Age  Gender spotify_usage_period  \
116  20-35    Male    More than 2 years   
117  20-35    Male    More than 2 years   
234  20-35  Female   Less than 6 months   
286  20-35  Female   6 months to 1 year   
288  20-35  Female    1 year to 2 years   
298  20-35  Female   6 months to 1 year   
305  20-35  Female    1 year to 2 years   
308  20-35  Female    1 year to 2 years   
314  20-35  Others    1 year to 2 years   
316  20-35  Female   6 months to 1 year   
479  20-35  Female   Less than 6 months   
481  20-35    Male   6 months to 1 year   

                              spotify_listening_device  \
116                                         Smartphone   
117                     Smartphone, Computer or laptop   
234                                         Smartphone   
286  Smartphone, Computer or laptop, Smart speakers...   
288  Computer or laptop, Smart speakers or voice as...   
298                                 Computer or laptop   
305                 Smart speakers or voice assistants   
308                                 Computer or laptop   
314                                 Computer or laptop   
316                 Smart speakers or voice assistants   
479                                 Computer or laptop   
481                                 Computer or laptop   

       spotify_subscription_plan premium_sub_willingness  \
116  Premium (paid subscription)                      No   
117  Premium (paid subscription)                      No   
234  Premium (paid subscription)                      No   
286  Premium (paid subscription)                      No   
288  Premium (paid subscription)                      No   
298  Premium (paid subscription)                      No   
305  Premium (paid subscription)                      No   
308  Premium (paid subscription)                      No   
314  Premium (paid subscription)                      No   
316  Premium (paid subscription)                      No   
479  Premium (paid subscription)                      No   
481  Premium (paid subscription)                      No   

       preffered_premium_plan preferred_listening_content fav_music_genre  \
116                       NaN                       Music       classical   
117                       NaN                       Music             All   
234    Duo plan- Rs 149/month                       Music          Melody   
286    Duo plan- Rs 149/month                     Podcast       classical   
288  Family Plan-Rs 179/month                     Podcast       classical   
298  Family Plan-Rs 179/month                       Music       classical   
305  Family Plan-Rs 179/month                       Music       classical   
308    Duo plan- Rs 149/month                     Podcast             Rap   
314  Family Plan-Rs 179/month                       Music       classical   
316  Family Plan-Rs 179/month                       Music          Melody   
479    Duo plan- Rs 149/month                       Music       classical   
481  Family Plan-Rs 179/month                     Podcast       classical   

    music_time_slot                             music_Influencial_mood  \
116           Night                       Relaxation and stress relief   
117           Night  Relaxation and stress relief, Uplifting and mo...   
234           Night                       Relaxation and stress relief   
286         Morning  Uplifting and motivational, Sadness or melancholy   
288       Afternoon  Uplifting and motivational, Sadness or melancholy   
298           Night                              Sadness or melancholy   
305           Night                              Sadness or melancholy   
308       Afternoon                         Uplifting and motivational   
314       Afternoon                         Uplifting and motivational   
316       Afternoon                              Sadness or melancholy   
479       Afternoon                         Uplifting and motivational   
481       Afternoon  

In [40]:
# 20대 이탈예상 고객의 음악 추천 평가 점수 
twenty_bounce['music_recc_rating'].mean()

# 평균 3.5보다 낮은 수치

2.5

In [43]:
twenty_bounce.groupby('preferred_listening_content').size()

preferred_listening_content
Music      8
Podcast    4
dtype: int64

In [44]:
twenty_bounce.groupby('fav_music_genre').size()

fav_music_genre
All          1
Melody       2
Rap          1
classical    8
dtype: int64

In [45]:
twenty_bounce.groupby('pod_variety_satisfaction').size()


pod_variety_satisfaction
Dissatisfied         1
Ok                   6
Satisfied            3
Very Dissatisfied    1
Very Satisfied       1
dtype: int64

- 만족 : 4
- 보통 : 6
- 불만족 : 2

In [52]:
#  retention 
# 프리미엄 구독중이고, 앞으로도 계속 구독 예정인 집단

twenty_reten = twenty[(twenty['spotify_subscription_plan']=='Premium (paid subscription)') & (twenty['premium_sub_willingness']=='Yes')]
twenty_reten.head()

Age  Gender spotify_usage_period  \
23  20-35  Female    More than 2 years   
24  20-35    Male    More than 2 years   
49  20-35    Male    1 year to 2 years   
59  20-35    Male    More than 2 years   
66  20-35    Male    More than 2 years   

                             spotify_listening_device  \
23  Smartphone, Computer or laptop, Smart speakers...   
24                     Smartphone, Computer or laptop   
49  Smartphone, Computer or laptop, Smart speakers...   
59               Computer or laptop, Wearable devices   
66  Smartphone, Computer or laptop, Smart speakers...   

      spotify_subscription_plan premium_sub_willingness  \
23  Premium (paid subscription)                     Yes   
24  Premium (paid subscription)                     Yes   
49  Premium (paid subscription)                     Yes   
59  Premium (paid subscription)                     Yes   
66  Premium (paid subscription)                     Yes   

            preffered_premium_plan preferred_listening_content  \
23  Individual Plan- Rs 119/ month                       Music   
24        Family Plan-Rs 179/month                       Music   
49  Individual Plan- Rs 119/ month                       Music   
59        Family Plan-Rs 179/month                       Music   
66  Individual Plan- Rs 119/ month                       Music   

     fav_music_genre music_time_slot  \
23         classical           Night   
24              Rock           Night   
49  Electronic/Dance           Night   
59               Pop           Night   
66            Melody           Night   

                               music_Influencial_mood  \
23  Relaxation and stress relief, Uplifting and mo...   
24  Relaxation and stress relief, Sadness or melan...   
49  Relaxation and stress relief, Uplifting and mo...   
59  Relaxation and stress relief, Uplifting and mo...   
66  Relaxation and stress relief, Uplifting and mo...   

                               music_lis_frequency  \
23  While Traveling, Workout session, leisure time   
24                                     Study Hours   
49  While Traveling, Workout session, leisure time   
59  While Traveling, Workout session, leisure time   
66  While Traveling, Workout session, leisure time   

                    music_expl_method  music_recc_rating  \
23  recommendations, Playlists, Radio                  1   
24             recommendations, Radio                  3   
49                    recommendations                  4   
59         recommendations, Playlists                  5   
66         recommendations, Playlists                  5   

       pod_lis_frequency         fav_pod_genre preffered_pod_format  \
23                Rarely                Comedy            Interview   
24                Rarely  Lifestyle and Health       Conversational   
49                Rarely                Comedy        Story telling   
59                 Never                   NaN                  NaN   
66  Several times a week                Comedy       Conversational   

   pod_host_preference preffered_pod_duration pod_variety_satisfaction  
23                Both                Shorter           Very Satisfied  
24                Both                   Both                       Ok  
49  unknown Podcasters                Shorter           Very Satisfied  
59                 NaN                    NaN                Satisfied  
66                Both                   Both           Very Satisfied

In [54]:
twenty_reten.groupby('preffered_premium_plan').size()

preffered_premium_plan
Duo plan- Rs 149/month             8
Family Plan-Rs 179/month           7
Individual Plan- Rs 119/ month    31
Student Plan-Rs 59/month           7
dtype: int64

In [55]:
twenty_reten.groupby('preferred_listening_content').size()

preferred_listening_content
Music      41
Podcast    13
dtype: int64

In [59]:
twenty_reten.groupby('fav_music_genre').size()

fav_music_genre
Electronic/Dance     3
Melody              20
Pop                 14
Rap                  9
Rock                 2
classical            6
dtype: int64

In [60]:
twenty_reten.groupby('pod_variety_satisfaction').size()

pod_variety_satisfaction
Dissatisfied       3
Ok                17
Satisfied         22
Very Satisfied    12
dtype: int64

- 만족: 34
- 보통: 17
- 불만족: 3

### 프리미엄 고객층 
---

In [62]:
premium_user = df[df['spotify_subscription_plan']=='Premium (paid subscription)']
premium_user

Age  Gender spotify_usage_period  \
23   20-35  Female    More than 2 years   
24   20-35    Male    More than 2 years   
26   12-20    Male   6 months to 1 year   
49   20-35    Male    1 year to 2 years   
59   20-35    Male    More than 2 years   
..     ...     ...                  ...   
506  20-35    Male   Less than 6 months   
508  12-20  Female   6 months to 1 year   
510  20-35    Male    More than 2 years   
518  20-35  Female   6 months to 1 year   
519  20-35  Female    More than 2 years   

                              spotify_listening_device  \
23   Smartphone, Computer or laptop, Smart speakers...   
24                      Smartphone, Computer or laptop   
26      Smartphone, Smart speakers or voice assistants   
49   Smartphone, Computer or laptop, Smart speakers...   
59                Computer or laptop, Wearable devices   
..                                                 ...   
506                 Smart speakers or voice assistants   
508                                   Wearable devices   
510                                         Smartphone   
518                                         Smartphone   
519                     Smartphone, Computer or laptop   

       spotify_subscription_plan premium_sub_willingness  \
23   Premium (paid subscription)                     Yes   
24   Premium (paid subscription)                     Yes   
26   Premium (paid subscription)                     Yes   
49   Premium (paid subscription)                     Yes   
59   Premium (paid subscription)                     Yes   
..                           ...                     ...   
506  Premium (paid subscription)                     Yes   
508  Premium (paid subscription)                     Yes   
510  Premium (paid subscription)                     Yes   
518  Premium (paid subscription)                     Yes   
519  Premium (paid subscription)                     Yes   

             preffered_premium_plan preferred_listening_content  \
23   Individual Plan- Rs 119/ month                       Music   
24         Family Plan-Rs 179/month                       Music   
26         Student Plan-Rs 59/month                     Podcast   
49   Individual Plan- Rs 119/ month                       Music   
59         Family Plan-Rs 179/month                       Music   
..                              ...                         ...   
506          Duo plan- Rs 149/month                       Music   
508          Duo plan- Rs 149/month                     Podcast   
510  Individual Plan- Rs 119/ month                       Music   
518  Individual Plan- Rs 119/ month                       Music   
519        Student Plan-Rs 59/month                       Music   

      fav_music_genre music_time_slot  \
23          classical           Night   
24               Rock           Night   
26                Rap         Morning   
49   Electronic/Dance           Night   
59                Pop           Night   
..                ...             ...   
506         classical         Morning   
508               Rap         Morning   
510            Melody           Night   
518            Melody           Night   
519               Pop           Night   

                                music_Influencial_mood  \
23   Relaxation and stress relief, Uplifting and mo...   
24   Relaxation and stress relief, Sadness or melan...   
26                        Relaxation and stress relief   
49   Relaxation and stress relief, Uplifting and mo...   
59   Relaxation and stress relief, Uplifting and mo...   
..                                                 ...   
506                         Uplifting and motivational   
508                       Relaxation and stress relief   
510  Relaxation and stress relief, Uplifting and mo...   
518  Relaxation and stress relief, Uplifting and mo...   
519  Relaxation and stress relief, Sadness or melan...   

                                   music_lis_frequency  \
23      While Trave

In [63]:
premium_user.groupby('Gender').size()

Gender
Female    66
Male      25
Others     5
dtype: int64

In [64]:
premium_user.groupby('Age').size()

Age
12-20    22
20-35    66
35-60     6
6-12      2
dtype: int64

In [70]:
premium_user.groupby('preffered_premium_plan').size()

preffered_premium_plan
Duo plan- Rs 149/month            26
Family Plan-Rs 179/month          17
Individual Plan- Rs 119/ month    36
Student Plan-Rs 59/month           9
dtype: int64

In [74]:
premium_user[premium_user['premium_sub_willingness']=='No'].shape


(24, 20)

In [75]:
premium_user.groupby('preferred_listening_content').size()

preferred_listening_content
Music      59
Podcast    37
dtype: int64